### PR TITLE
Issue 02 Resolved

### PR DESCRIPTION
**Pull request by AliAzaz**
Fixed issue #02, updated SplashScreenActivity, and some minor modifications.
There is no wireframes are available that's why I updated it with a simple one:

image

Note: Appname would replace with username and android image would replace with person image.

### CODE REVIEW

**Comment by Shobu95** [comment]
@AliAzaz . Thank you so much Ali bhai for your contribution. I ll mark this PR as hacktoberfest-accepted and merge it once the event ends. Looking forward to more contributions from you. Happy Hacking. <3

**Comment by Shobu95** [comment]
@AliAzaz bhai can you update your PR because you have submitted it into the main branch. PLease update it and make a PR into the develop branch. Thank You.

**Comment by AliAzaz** [comment]
Sorry @Shobu95 for that

**Comment by AliAzaz** [comment]
Please merge this branch so I could work on your splashscreen issue

**Pull request merged**
