### PR TITLE
Issue 1 siddharth

### PR DESCRIPTION
**Pull request by SiddyDevelops**
Sir I have made the required changes:
Added different animation which reflect cash and credit card
Change the background color of splash screen.

### CODE REVIEW

**Comment by Shobu95** [comment]
Can you send a Screenshot/video of your splash screen ???

**Comment by SiddyDevelops** [comment]
Screenshot_20211005-204328_CreBits
This is the screenshot.

**Comment by Shobu95** [comment]
@SiddyDevelops GREAT WORK Siddharth. Your PR will be marked as hacktoberfest-accepted. Also, if you like my project, give it a STAR. Thank you for your contribution.

Keep Hacking!!!!!!

**Comment by SiddyDevelops** [comment]
Sir, won't you merge it and close this issue?

**Comment by Shobu95** [comment]
@SiddyDevelops yes Siddharth i will merge and close, but there is a chance that more contributors may want to contribute to the same issue, so i ll merge it once Hacktoberfest ends.
However, your PR has been given the **Hacktoberfest-accepted** label, so dont worry your PR is an accepted contribution. 
Thank you once again.

**Comment by SiddyDevelops** [comment]
Okay thank you sir, I enjoyed contributing with you.

**Pull request merged**
